// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/devanadindra/portfolio/back-end/database"
	"github.com/devanadindra/portfolio/back-end/domains/certif"
	"github.com/devanadindra/portfolio/back-end/domains/project"
	"github.com/devanadindra/portfolio/back-end/domains/skill"
	"github.com/devanadindra/portfolio/back-end/domains/user"
	"github.com/devanadindra/portfolio/back-end/middlewares"
	"github.com/devanadindra/portfolio/back-end/routes"
	"github.com/devanadindra/portfolio/back-end/utils/config"
	"github.com/devanadindra/portfolio/back-end/utils/dbselector"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

import (
	_ "github.com/google/subcommands"
)

// Injectors from wire.go:

func initializeDependency(config2 *config.Config) (*routes.Dependency, error) {
	ownerDB, err := database.NewDBAdmin(config2)
	if err != nil {
		return nil, err
	}
	visitorsDB, err := database.NewDBCustomer(config2)
	if err != nil {
		return nil, err
	}
	dbService := dbselector.NewDBService(ownerDB, visitorsDB)
	service := user.NewService(config2, dbService, visitorsDB, ownerDB)
	middlewaresMiddlewares := middlewares.NewMiddlewares(config2, service)
	validate := validator.New()
	handler := user.NewHandler(service, validate)
	projectService := project.NewService(config2, dbService, visitorsDB, ownerDB)
	projectHandler := project.NewHandler(projectService, validate)
	skillService := skill.NewService(config2, dbService, visitorsDB, ownerDB)
	skillHandler := skill.NewHandler(skillService, validate)
	certifService := certif.NewService(config2, dbService, visitorsDB, ownerDB)
	certifHandler := certif.NewHandler(certifService, validate)
	dependency := routes.NewDependency(config2, middlewaresMiddlewares, ownerDB, visitorsDB, handler, projectHandler, skillHandler, certifHandler)
	return dependency, nil
}

// wire.go:

var dbSet = wire.NewSet(database.NewDBCustomer, database.NewDBAdmin)

var dbSelectorSet = wire.NewSet(dbselector.NewDBService)

var userSet = wire.NewSet(user.NewService, user.NewHandler)

var projectSet = wire.NewSet(project.NewService, project.NewHandler)

var skillSet = wire.NewSet(skill.NewService, skill.NewHandler)

var certifSet = wire.NewSet(certif.NewService, certif.NewHandler)
