// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/devanadindra/portfolio/back-end/database"
	"github.com/devanadindra/portfolio/back-end/domains/kamus"
	"github.com/devanadindra/portfolio/back-end/domains/kuis"
	"github.com/devanadindra/portfolio/back-end/domains/skill"
	"github.com/devanadindra/portfolio/back-end/domains/user"
	"github.com/devanadindra/portfolio/back-end/middlewares"
	"github.com/devanadindra/portfolio/back-end/routes"
	"github.com/devanadindra/portfolio/back-end/utils/config"
	"github.com/devanadindra/portfolio/back-end/utils/dbselector"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

import (
	_ "github.com/google/subcommands"
)

// Injectors from wire.go:

func initializeDependency(config2 *config.Config) (*routes.Dependency, error) {
	ownerDB, err := database.NewDBAdmin(config2)
	if err != nil {
		return nil, err
	}
	visitorsDB, err := database.NewDBCustomer(config2)
	if err != nil {
		return nil, err
	}
	dbService := dbselector.NewDBService(ownerDB, visitorsDB)
	service := user.NewService(config2, dbService, visitorsDB, ownerDB)
	middlewaresMiddlewares := middlewares.NewMiddlewares(config2, service)
	validate := validator.New()
	handler := user.NewHandler(service, validate)
	kamusService := kamus.NewService(config2, dbService, visitorsDB, ownerDB)
	kamusHandler := kamus.NewHandler(kamusService, validate)
	skillService := skill.NewService(config2, dbService, visitorsDB, ownerDB)
	skillHandler := skill.NewHandler(skillService, validate)
	kuisService := kuis.NewService(config2, dbService, visitorsDB, ownerDB)
	kuisHandler := kuis.NewHandler(kuisService, validate)
	dependency := routes.NewDependency(config2, middlewaresMiddlewares, ownerDB, visitorsDB, handler, kamusHandler, skillHandler, kuisHandler)
	return dependency, nil
}

// wire.go:

var dbSet = wire.NewSet(database.NewDBCustomer, database.NewDBAdmin)

var dbSelectorSet = wire.NewSet(dbselector.NewDBService)

var userSet = wire.NewSet(user.NewService, user.NewHandler)

var kamusSet = wire.NewSet(kamus.NewService, kamus.NewHandler)

var skillSet = wire.NewSet(skill.NewService, skill.NewHandler)

var kuisSet = wire.NewSet(kuis.NewService, kuis.NewHandler)
